[package]
name = "cli"
version = "0.1.0"
authors = ["Toshiaki Takada <toshiaki.takada@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2.18"
quick-error = "1.2.2"
#rustyline = "3.0.0"
#rustyline = { git = "https://github.com/sjtakada/rustyline", branch = "custom" }
rustyline = { path = "/home/toshiaki/git/rustyline" }
serde_json = "1.0.38"
mio = "0.6.16"
mio-uds = "0.6.7"
#libc = "0.2.51"
nix = "0.13.0"
#signal-hook = "0.1.8"
